### ISSUE TITLE
Set worker to never timeout.

### ISSUE THREAD

**Issue by mathnitin** [brigadecore/brigade#1150] opened 2020-10-26 07:36 UTC
Is there a way to set the worker to never timeout? I set a timeout for my job as a random value between 30 to 60 minutes, but the worker times out after 15 minutes. I understand the default worker timeout is 15 minutes. 

Is there something I can do for worker to never timeout and always wait for the job to finish? Or something in my javascript to ignore the timeout completely?

Any pointer is appreciated. Thanks in advance.

**Comment by krancour** [comment] 2020-10-27 00:56
There actually isn't any timeout on the worker-- neither configurable nor hard-coded. Only jobs have a timeout. 

Can you elaborate on exactly what you see happening and perhaps share some output, or even better, a minimal script to reproduce the problem?

**Comment by mathnitin** [comment] 2020-10-27 17:47
@krancour Below is the exception I am seeing.
```
[  Error: time limit (900000 ms) exceeded

  - k8s.js:670 Timeout._onTimeout
    /home/src/dist/k8s.js:670:24

  - timers.js:549 listOnTimeout
    internal/timers.js:549:17

  - timers.js:492 processTimers
    internal/timers.js:492:7

]
```
I can see the below Error is coming from  https://github.com/brigadecore/brigade/blob/v1.4.0/brigade-worker/src/k8s.ts#L792
Also on the documentation page, i can see https://docs.brigade.sh/topics/scripting/
```
Timeout set at 900000
```

**Comment by krancour** [comment] 2020-10-27 20:52
@mathnitin that's the timeout on the _job_. The worker doesn't have a timeout.

**Comment by tomfotherby** [comment] 2020-10-28 15:47
@mathnitin - We have Brigade Projects that last hours. The worker itself doesn't timeout (assuming the Node it's hosted on doesn't get terminated).

The trick I use is to create a class that sets all the defaults I use for Jobs, including increasing the timeout, e.g.

```js
// Convinience class so usual defaults are set, and a consistent alpine tag is used.
class AlpineJob extends Job
{
  constructor(name,tasks) {
    super(name, "alpine:3.12",tasks);

    // Speed up the Pod start by not downloading the git repo
    this.useSource = false

    this.timeout = 3600000; // 3600000ms is 1 hour. Default is 900000ms (15 minutes)

    // Our scripts often operate on storaged files downloaded in prior steps
    this.storage.enabled = true

    this.resourceRequests.cpu = "50m"
    this.resourceLimits.cpu = "500m"
    this.resourceRequests.memory = "32Mi"
    this.resourceLimits.memory = "256Mi"
  }
}
```

```
    var job = new AlpineJob("show-sql-files", ['ls /mnt/brigade/share/ds_scripts/*.sql']);
    await job.run();
```

**Comment by mathnitin** [comment] 2020-10-31 00:36
@tomfotherby Thanks, I am using a class. Creating Jobs and Groups. I will try to create a test script and share in a day or two.

**Comment by krancour** [comment] 2020-10-31 12:58
Closing this issue since it's been sufficiently established that workers do not in fact time out.

**Closed by krancour** 2020-10-31 12:58 UTC
