### ISSUE TITLE
using brigade.js as a submodule

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1102] opened 2020-07-13 22:49 UTC
Hi,

I would like to create a GitLab repository and use the repository in another Gitlab repositories as a submodule. When I change/add a new feature into the brigade repository all the Gitlab repositories can be updated and use the new features or changes. 

for this, I created a simple export function in brigade.js file
 ```
 export function getUsefulContents(url) {
    console.log (url)
  }
```

and use it in brigade-local.js file

```
import * as myModule from './brigade.js';

myModule.getUsefulContents('http://www.example.com');
```
package.json file 

```
{
    "type": "module"
}
```
When I run it from a command file 

```
node brigade-local.js
http://www.example.com
```

When I run the test inside K8s with brig command 

`brig run --no-progress -e runsimpletest  -f brigade-local.js -p payload.json`

 ```
SyntaxError: Cannot use import statement outside a module.
```

I tried to use brigade.json file for the set the module like in package.json file for node command but it did not work.

Can we use brigade.js' functions, class as exportable and use in a different  JS file such as brigade-local.js file?  Can you share an example for it?

Output of `brig version`: 1.40 943d43e

Output of `kubectl version`: 1.18.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): baremetal

**Comment by krancour** [comment] 2020-07-14 00:18
This issue is lacking too much context, such as project configuration, to know the root cause with certainty, but I can take a guess...

```
brig run --no-progress -e runsimpletest -f brigade-local.js -p payload.json
```

This command includes the _local_ file `brigade-local.js` in the event that it creates and sends to Brigade. That file attempts to import code from `./brigade.js`, but where or how is it to find that file?

Again, this is where I can't know for sure what's going on because I haven't seen your project configuration, but unless your project is configured as a "VCS" project and set up properly to clone source from your git repo, there's no reason you should expect this to work because the `./brigade.js` file referenced by your `brigade-local.js` file doesn't exist as far as the worker running the script is concerned.

**Comment by krancour** [comment] 2020-07-14 00:39
Happy to figure out what else might be going on if more context is provided.

**Comment by kenotsolutions** [comment] 2020-07-14 15:30
Hi,

This is a VCS project and both of the js file in the same directory so it should not any problem `brigade-local.js` import `brigade.js` file.  

I added the `runsimpletest` function in  brigade.js and brigade-local.js file. 

you can run 
`brig run --no-progress -e runsimpletest -f brigade-local.js -p payload.json`

gzip file
[brigade.gz](https://github.com/brigadecore/brigade/files/4919678/brigade.gz)

**Comment by krancour** [comment] 2020-07-21 19:51
@kenotsolutions I just got around to looking at this. Unfortunately, the archive you attached isn't quite enough to go on. I'd have to see things like how the project is defined.

**Comment by kenotsolutions** [comment] 2020-07-22 18:33
`brig project get test -n brigade

typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: brigade-xxxxx
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels:
    app: brigade
    component: project
    heritage: brigade
  annotations:
    projectName: test
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
immutable: null
data: {}
stringdata:
  allowHostMounts: "false"
  allowPrivilegedJobs: "true"
  brigadeConfigPath: ""
  brigadejsPath: ""
  buildStorageSize: 300Mi
  cloneURL: git@something:testme/test.git
  defaultConfig: ""
  defaultConfigName: ""
  defaultScript: ""
  defaultScriptName: ""
  genericGatewaySecret: ""
  github.baseURL: ""
  github.token: ""
  github.uploadURL: ""
  initGitSubmodules: "true"
  kubernetes.allowSecretKeyRef: "false"
  kubernetes.buildStorageClass: ""
  kubernetes.cacheStorageClass: ""
  namespace: brigade
  repository: something:testme/test
  secrets: ''
  serviceAccount: brigade-worker
  sharedSecret: sdfsdfdsf
  sshCert: ""
  sshKey: ""--
  vcsSidecar: brigadecore/git-sidecar:latest
  worker.name: ""
  worker.pullPolicy: Always
  worker.registry: ""
  worker.tag: ""
  workerCommand: ""
type: brigade.sh/project`

**Comment by krancour** [comment] 2021-09-23 22:45
Closing due to staleness. Please do re-open if appropriate.

**Closed by krancour** 2021-09-23 22:45 UTC
