### ISSUE TITLE
brigade docker:dind false-positive exit code 

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1140] opened 2020-10-22 12:19 UTC
Brigade sometimes could not determine exit code from some events run with `docker:dind` image.

I tried to run it with `try catch  control` the event gives false-positive results. Some times it fails and sometimes it passes. I also add events.on("error", to add one more control. 

`brig run --no-progress -e testdind brigade.js -p payload.json   || (echo "brigade step failed $?"; exit 1)`

```
events.on("testdind", (event, project) => {
    var beTestter = new Job ("testme","docker:dind")

    beTestter.privileged = true
    beTestter.serviceAccount = "brigade-installer";
   
    beTestter.tasks = [
        `exit 1`
    ]
    try {
        beTestter.run()
    } catch (event) {
        console.log(`Caught Exception ${event}`);
        process.exit (event)
    }
})

events.on("error", () => {
    console.log(" **** ERROR EVENT called")
    process.exit(12);
    throw Error(` Please check the error`);
  })
``

**Comment by krancour** [comment] 2020-10-22 16:56
> I also add events.on("error", to add one more control.

You cannot expect the `error` event to ever fire because your `catch` block handled the error _and_ forced the process to exit.

As for why this is happening in the first place...

Here's a simple test to show the Docker image works as expected:

```console
docker run -it docker:dind sh -c "exit 1"
```

This reliably works. And we use `docker:dind` extensively without any issues in Brigade's own builds.

I think this narrows the issue down to something with your script.

```
try {
        beTestter.run()
    } catch (event) {
        console.log(`Caught Exception ${event}`);
        process.exit (event)
    }
```

Something looks off here. Admittedly, JS is not my strong point. I usually lean on other maintainers for JS-related things, _but_ unless I am mistaken, the problem is that `beTestter.run()` returns a promise, _but you're not waiting on that promise_. You're just moving on immediately. I'm not at all clear on why that's sometimes resulting in an error and sometimes not, but I'm 99% sure it's not what you actually intend to do here.

Consider re-writing this in one of two ways and see if it improves your results:

Option 1:

```
beTestter.run().then(res => {
  // Handle success
}).catch(err => {
  // Handle error
});
```

Or option 2-- a slightly larger refactor, but clearer code:

```
events.on("testdind", testdind);

async function testdind(event, project) {
  // ...
  try {
    await res = beTestter.run();
    // Handle success
  }
  catch(err) {
    // Handle error
  }
}
```

Let me know how this works out for you.

**Comment by kenotsolutions** [comment] 2020-10-22 17:41
Hi,

This looks like my actual code and still, brigade cannot determine the exit code 
```

////
// class
////
class CreateEnvC extends Job {

    constructor(event, project) {
        try {
            const payload = JSON.parse(event.payload);

            var job_name = Math.floor(Math.random()*90000) + 10000;
            super(job_name, event, "docker:dind")
            
            this.privileged = true
            this.timeout = 1800000
             this.tasks.push( 
                `exit 1`,
            )
            console.log(this.tasks)
        } catch (error) {
            logError(error);
     
        }
    }
}

////
// function
////
async function createEnvFn (event, project) {
    try {
        await new CreateEnvC(event, project).run();
    } catch (error) {
        console.log(`Caught Exception ${event}`);
        process.exit (event)
    } 
}

////
// event
////
events.on("create-env", createEnvFn);
```

I tried to simplify the code.

**Comment by krancour** [comment] 2020-10-22 17:47
Have a closer look at this:

```javascript
async function createEnvFn (event, project) {
    try {
        await new CreateEnvC(event, project).run();
    } catch (error) {
        console.log(`Caught Exception ${event}`);
        process.exit (event)
    } 
}
```

You're referencing `event` in places where I believe you intended to reference `error`.

**Comment by kenotsolutions** [comment] 2020-10-22 17:49
it is a typo

**Comment by krancour** [comment] 2020-10-22 17:52
@kenotsolutions can you correct it / provide a minimally reproducible example and I'll see if I can get to the bottom of it?

**Comment by kenotsolutions** [comment] 2020-10-22 17:55
You can check it the above the code.  

Please check at least 10 times. 
brig run --no-progress -e create-env brigade.js -p payload.json || (echo "brigade step failed $?"; exit 1) 

Thanks

**Comment by krancour** [comment] 2020-10-22 18:46
@kenotsolutions that's not really a minimal example, but I'll try it.

**Comment by krancour** [comment] 2020-10-25 00:40
@kenotsolutions I've played around with your script a little and I can't event get it to run without several modifications.

The biggest problem seem to be that the arguments you pass to the `CreateEnvC` class' superclass' constructor are incorrect.

```javascript
class CreateEnvC extends Job {

  constructor(event, project) {
      try {
          // ...
          super(job_name, event, "docker:dind")
          // ^^^ The arguments passed here do not match the arguments expected by the superclass' constuctor
          // ...
      } catch (error) {
          // ...
      }
  }
}
```

This does not match what is in the brigadier librarie's `Job` class:

```
constructor(
    name: string,
    image?: string,
    tasks?: string[],
    imageForcePull: boolean = false
 ) {
  // ...
}
```

**Comment by kenotsolutions** [comment] 2020-10-29 18:34
Please check the example. This event should give a syntax error because using `await` in the event. 


When I run the below command I am expecting to see `brigade step failed` message but it runs and finishes with no errors.
 
`brig run --no-progress -e error_script  -f brigade.js -p payload.json -r master "brig-error-project"  || (echo "brigade step failed $?"; exit 1)`
 
```
[/etc/brigade/..2020_10_29_18_22_40.639896423/script:7
events.on("error_script", await abcd);
                          ^^^^^

  SyntaxError: missing ) after argument list

  - loader.js:1070 wrapSafe
    internal/modules/cjs/loader.js:1070:16

  - loader.js:1120 Module._compile
    internal/modules/cjs/loader.js:1120:27

  - loader.js:1176 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1176:10

  - loader.js:1000 Module.load
    internal/modules/cjs/loader.js:1000:32

  - loader.js:899 Function.Module._load
    internal/modules/cjs/loader.js:899:14

  - loader.js:1042 Module.require
    internal/modules/cjs/loader.js:1042:19

  - helpers.js:77 require
    internal/modules/cjs/helpers.js:77:18

  - index.js:96 Object.<anonymous>
    /home/src/dist/index.js:96:5

  - loader.js:1156 Module._compile
    internal/modules/cjs/loader.js:1156:30

  - loader.js:1176 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1176:10

```

The code exit with 0 (no error)

`echo $?`

0

the pod failed in the Kubernetes env.

`kubectl get pods brigade-worker-01entsh01bmgfmtbcqczn8dne5 -n brigade`

```
NAME                                        READY   STATUS   RESTARTS   AGE
brigade-worker-01entsh01bmgfmtbcqczn8dne5   0/1     Error    0          5m31s
```
-----------------------------

cat brigade.js

```
const {
    events,
    Job,
    Group
} = require('brigadier')

events.on("error_script", await abcd);

```

**Comment by krancour** [comment] 2020-10-29 19:00
> Please check the example.

@kenotsolutions I did try to run your example, as I indicated. There are obvious problems with it which I highlighted. I haven't seen you respond to that.

To level set on expectations, if you want project maintainers to assist you with your issue, furnishing a _minimal_ reproducible example is the best way to hep us help you. In many cases, the exercise of doing that may lead you to your own answer.

I won't be spending more time to troubleshoot the non-minimal script you provided.

**Comment by kenotsolutions** [comment] 2020-10-29 19:06
@krancour  Thanks for the help but this is not my issue this brigade's issue. I am trying to prove you that brig cannot catch failed pod's exit code. In the second example, there is not an extra class just a simple event which gives a syntax error but brig cannot catch its error and exit without error.

**Comment by krancour** [comment] 2020-10-29 20:09
@kenotsolutions I understand what you are trying to prove to me.

> In the second minimal reproducible example, there is not an extra class...

Where is this example? I don't see it anywhere in the backscroll.

**Comment by kenotsolutions** [comment] 2020-10-29 20:16
cat brigade.js

This the code no function no class nothing but the event

```
const {
    events,
    Job,
    Group
} = require('brigadier')

events.on("error_script", await abcd);

```
**await**  the error


This is how to run it.

`brig run --no-progress -e error_script -f brigade.js -p payload.json -r master "brig-error-project" || (echo "brigade step failed $?"; exit 1)`

this is what es expected `brigade step failed`

this is what is the result 

```
[/etc/brigade/..2020_10_29_18_22_40.639896423/script:7
events.on("error_script", await abcd);
                          ^^^^^

  SyntaxError: missing ) after argument list

  - loader.js:1070 wrapSafe
    internal/modules/cjs/loader.js:1070:16

```
`echo $?`
0

**Comment by krancour** [comment] 2020-10-29 20:26
```
const {
    events,
    Job,
    Group
} = require('brigadier')

events.on("error_script", await abcd);
```

@kenotsolutions that does not look like a complete or syntactically correct script.

Where is the symbol `abcd` defined?

How about the misplaced `await` keyword?

The errors you are receiving are precisely what I expect for an invalid script such as this one.

As for why that exits `0`-- it's because `brig run` creates an event and streams the worker's logs. `brig run` _was_ successful at doing this. The outcome of the build doesn't affect the outcome of the `brig run` command. See here:

https://github.com/brigadecore/brigade/blob/master/brig/cmd/brig/commands/run.go#L141-L148

I don't see how any of this is connected to the original complain of false positives for jobs using the `docker:dind` image.

**Comment by kenotsolutions** [comment] 2020-10-29 21:10
I know this is not connected with dind,  and there is not abcd function and I put the wrong syntax there to it fails.

 What I am trying to show brig created a worker pod and the worker pod finished with **error**.  Brig should return the worker pod **status** which is Error but it finishes without error.  What should we wait here? pass or fail. 

`kubectl get pods brigade-worker-01entsh01bmgfmtbcqczn8dne5 -n brigade`

```
NAME                                        READY   STATUS   RESTARTS   AGE
brigade-worker-01entsh01bmgfmtbcqczn8dne5   0/1     Error    0          5m31s
```

When we run our tests we also see the same results some of our events finish with error but brig cannot catch them but sometimes it catches.

**Comment by krancour** [comment] 2020-10-29 21:56
> I know this is not connected with dind

The title of this issue and your original example specifically noted false positives when using `docker:dind`. That is the core issue I've been focused on troubleshooting all along. If at some point you decided to make this conversation about a _different_ issue, that wasn't entirely clear to me until recently.

> Brig should return the worker pod status which is Error but it finishes without error.

Per my comment and reference to relevant code, _by design_, that isn't what it does.

> As for why that exits `0`-- it's because brig run creates an event and streams the worker's logs. `brig run` was successful at doing this. The outcome of the build doesn't affect the outcome of the `brig run` command. See here:
>
> https://github.com/brigadecore/brigade/blob/master/brig/cmd/brig/commands/run.go#L141-L148

_I can very clearly see why someone might expect otherwise._ `brig run` is misleading terminology as it implies that it directly runs your script, but it does not. It creates an event (aka "build") and that event is handled asynchronously. _If event creation succeeded, it exits 0._

fwiw, Brigade 2 is doing away with `brig run` in favor of `brig event create`, because it makes the behavior quite a bit more clear.

Obviously, we cannot change the behavior in Brigade 1.x because it would be a breaking change.

> When we run our tests we also see the same results some of our events finish with error but brig cannot catch them but sometimes it catches.

Not to sound like a broken record, but `brig run` is not meant to catch errors in your script. If you want an accurate indicator of worker success or failure, use `brig build get <build id>`.

Remember also that the primary use case for Brigade is _automation_. A _gateway_ receives an event from some upstream system (like GitHub, Docker Hub, Slack, etc.) and "emits" that event into Brigade where it is handled asynchronously. `brig run` is mainly used for creating events to help _troubleshoot_ your script and it's not a typical component of a real life workflow-- meaning that its lack of connection to the success or failure of the worker is not usually of any consequence.

**Comment by kenotsolutions** [comment] 2020-11-02 22:55
Thanks for the explanation. 

As you know each step depends on the previous step result in GitOps and Gitlab-ci.yaml 

Let's assume the first step create a namespace with brig run then after the second step is deploy a manifest file in the namespace so if it is an async event and we cannot capture its results how can we sure the namespace created and how can we deploy the manifest file into the namespace. We have to get the exec exit code for each step from `brig run`.


Dockerfile for harbor image 
harbor.abc.com/library/base:v-1"

```
FROM alpine:3.9.5 
RUN apk update && apk add git && apk add docker && apk add screen 
ADD https://storage.googleapis.com/kubernetes-release/release/v1.16.3/bin/linux/amd64/kubectl /usr/local/bin/kubectl
RUN chmod +x /usr/local/bin/kubectl 
```



```
stages:
  - create-namespace
  - deploy-manifest


create-namespace-job:
  stage: create-namespace
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:stable-dind
  script:
    - make -C GITOPS create-namespace 
     
deploy-manifest-job:
  stage:   deploy-manifest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:stable-dind
  script:
    - make -C GITOPS deploy-manifest

```

cat GITOPS/Makefile

```

create-namespace:
	brig run --no-progress -e create-namespace    -f local-brigade.js -p payload.json -r master  "brg-service"  -n brigade || (echo "brigade step failed $$?"; exit 1)  

deploy-manifest:   
        brig run --no-progress -e deploy-manifest    -f local-brigade.js -p payload.json -r master  "brg-service"  -n brigade || (echo "brigade step failed $$?"; exit 1)  
```



brigade.js
```
const baseImage = "harbor.abc.com/library/base:v-1"

events.on("create-namespace", (event, project) => {
    var beTestter = new Job ("create",baseImage)
   
    beTestter.tasks = [
        `kubectl create namespace test123`,
    ]


    try {
        beTestter.run()
    } catch (err) {
        console.log(`Caught Exception ${event}`);
        process.exit (err)
    } 
    
})


events.on("deploy-manifest, (event, project) => {
    var beTestter = new Job ("deploy",baseImage)
   
    beTestter.tasks = [
        `kubectl run nginx --image=nginx --restart=Always -n test123`,
    ]

    try {
        beTestter.run()
    } catch (err) {
        console.log(`Caught Exception ${event}`);
        process.exit (err)
    } 
    
})



```

**Comment by krancour** [comment] 2020-11-03 00:12
@kenotsolutions you are not using Brigade as intended.

Events in Brigade are discrete and not related to one another. You don't create workflows by firing one event after another. You create workflows through a `brigade.js` script that handles _a single event_ by executing jobs either concurrently or in sequence.

To be frank, I'm confused at why you're using gitlab and Brigade together. There's considerable overlap in their feature sets. I'm no gitlab expert, but here you appear to be responding to some event in gitlab by creating containerized jobs that fire off events to Brigade........ to create containerized jobs. Why use two different systems that basically do the same thing? It seems an undesirable degree of complexity. Pick one.

At any rate, I am closing this issue now because the original complaint ("brigade docker:dind false-positive exit code") was found not to be credible and has been addressed. The conversation has shifted several times, so this thread for quite some time now has not been about any one discrete issue; rather it's become a time-consuming thread wherein I'm being asked to troubleshoot your invalid scripts and convoluted workflow. That's not what this forum is for.

If you need further assistance, I would suggest a more careful reading of the docs and/or posting to the Brigade channel in the Kubernetes Slack.

**Closed by krancour** 2020-11-03 00:12 UTC
